---
title: "Data Storytelling"
author: "Victor H. Ayala Sánchez"
date: "16/5/2022"
output: 
 html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, include=FALSE, message=FALSE}

### Librerias
library(forcats)
library(dplyr)
library(knitr)
library(ggplot2)
library(readr)
library(kableExtra)

```

# Introducción


```{r, warning=FALSE, include=FALSE, message=FALSE}
df <- read_csv("data/bestsellers_with_categories_2022_03_27.csv")
df$Rating <- round(df$`User Rating`)
df$Rating <- as.factor(df$Rating)
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
kable(head(df, 5), booktabs = TRUE) %>% kable_styling(latex_options = "scale_down", font_size = 12)
```

# Análisis de los libros vendidos en Amazon

## Frecuencias por Año {.tabset .tabset-fade .tabset-pills}


### 2009-2012

```{r, echo=FALSE}
df %>% 
  filter(Year == 2009 | Year == 2010 | Year ==  2011 | Year ==  2012) %>%
  group_by(Genre) %>% summarise(Count = n()) %>% 
  mutate(Genre = fct_reorder(Genre, desc(Count))) %>%
  ggplot(aes(x = Genre, y = Count, fill=Genre)) + geom_bar(stat = "identity", show.legend = FALSE, width = 0.5) + 
  theme_minimal() + 
  ylab("Frecuencia")
```


### 2013-2016

```{r, echo=FALSE}
df %>% 
  filter(Year == 2013 | Year == 2014 | Year ==  2015 | Year ==  2016) %>%
  group_by(Genre) %>% summarise(Count = n()) %>% 
  mutate(Genre = fct_reorder(Genre, desc(Count))) %>%
  ggplot(aes(x = Genre, y = Count, fill=Genre)) + geom_bar(stat = "identity", show.legend = FALSE, width = 0.5) + 
  theme_minimal() + 
  ylab("Frecuencia")
```

### 2017-2020
```{r, echo=FALSE}
df %>% 
  filter(Year == 2017 | Year == 2018 | Year ==  2019 | Year ==  2020) %>%
  group_by(Genre) %>% summarise(Count = n()) %>% 
  mutate(Genre = fct_reorder(Genre, desc(Count))) %>%
  ggplot(aes(x = Genre, y = Count, fill=Genre)) + geom_bar(stat = "identity", show.legend = FALSE, width = 0.5) + 
  theme_minimal() + 
  ylab("Frecuencia")
```

### 2021-2022

```{r, echo=FALSE}
df %>% 
  filter(Year == 2021 | Year == 2022) %>%
  group_by(Genre) %>% summarise(Count = n()) %>% 
  mutate(Genre = fct_reorder(Genre, desc(Count))) %>%
  ggplot(aes(x = Genre, y = Count, fill=Genre)) + geom_bar(stat = "identity", show.legend = FALSE, width = 0.5) + 
  theme_minimal() + 
  ylab("Frecuencia")
```


## Número de reviews en función del Rating {.tabset .tabset-fade .tabset-pills}

### Género Fiction

```{r, echo=FALSE}
df %>% 
  filter(Genre == "Fiction" & Rating != 3) %>%
  ggplot(aes(x = Rating, y = Reviews, fill=Rating, color = Rating)) + 
  geom_boxplot()
```


### Género No Fiction

```{r, echo=FALSE}
df %>% 
  filter(Genre == "Non Fiction") %>%
  ggplot(aes(x = Rating, y = Reviews, fill=Rating, color = Rating)) + 
  geom_boxplot()
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
df %>% group_by(Year) %>% summarise(Count = n())
```


```{r}
df %>%
  ggplot(aes(x = Price, color = Genre, fill = Genre)) + facet_wrap(~Rating) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```




```{r}
df %>%
  ggplot(aes(x = Reviews, color = Genre, fill = Genre)) + facet_wrap(~Genre) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```

```{r}
df %>%
  ggplot(aes(x = Price, color = Genre, fill = Genre)) + facet_wrap(~Genre) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```


```{r}
df %>%
  ggplot(aes(x = Price, color = Genre, fill = Genre)) + facet_wrap(~Year) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```

```{r}
df %>%
  filter(Year == 2009 | Year == 2010 | Year ==  2011) %>%
  ggplot(aes(x = Price, color = Genre, fill = Genre)) + facet_wrap(~Year) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```
```{r}
df %>%
  #filter(Year == 2009 | Year == 2010 | Year ==  2011) %>%
  group_by(Year, Genre) %>%
  summarise(Mean_Price = mean(Price)) %>%
  ggplot(aes(x = Year, y = Mean_Price, fill = Genre, color =Genre)) +
  geom_line(alpha = 0.75, show.legend = T) + 
  scale_x_discrete(limits = c(2009:2022), expand = c(0,0)) +
  theme_minimal() +
  ylab("Precio Promedio") + 
  xlab("")
```

```{r}
df %>%
  ggplot(aes(x = `User Rating`, color = Genre, fill = Genre)) + facet_wrap(~Genre) +
  geom_histogram(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```


```{r}

df %>%
  ggplot(aes(x = Genre, y = Reviews, color = Genre, fill = Genre)) +
  geom_boxplot(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```

```{r}
df %>%
  ggplot(aes(x = Genre, y = Price, color = Genre, fill = Genre)) +
  geom_boxplot(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```

```{r}
df %>%
  ggplot(aes(x = Genre, y = `User Rating`, color = Genre, fill = Genre)) +
  geom_boxplot(alpha = 0.75, show.legend = T) + 
  theme_minimal()
```

```{r}
df %>% group_by(Author) %>% summarise(Count = n()) %>% arrange(desc(Count)) %>% head()
```


```{r}
df %>% group_by(Author) %>% summarise(Count = n(),
                                      Mean_Price = mean(Price)) %>% arrange(desc(Count)) %>% head(5)
```


```{r}
df %>% filter(Author == "Gary Chapman" | Author == "Jeff Kinney" | Author == "Suzanne Collins") %>%
  ggplot(aes(x = Price))  +
  geom_histogram(alpha = 0.75, show.legend = T)
  theme_minimal()
```



```{r}
df %>%
  ggplot(aes(x = Reviews,y = Price)) + 
  geom_point(alpha = 0.75, color = "#005CAB") + geom_smooth(method = "lm") +
  theme_minimal()
```

```{r}
df %>%
  ggplot(aes(x = `User Rating`,y = Price)) + 
  geom_point(alpha = 0.75, color = "#005CAB") + geom_smooth(method = "lm") +
  theme_minimal()
```



# Conclusión


